/* 408 Observatory — interaction orchestration and accessible controls. */
'use strict';
const ICONS={
  memory:'<svg viewBox="0 0 24 24" fill="none"><rect x="5" y="4" width="14" height="16" rx="2" stroke="currentColor"/><path d="M8 8h8M8 12h5M8 16h7" stroke="currentColor"/></svg>',
  cache:'<svg viewBox="0 0 24 24" fill="none"><rect x="6" y="6" width="12" height="12" rx="2" stroke="currentColor"/><path d="M9 3v3m3-3v3m3-3v3M9 18v3m3-3v3m3-3v3M3 9h3m-3 3h3m-3 3h3m12-6h3m-3 3h3m-3 3h3" stroke="currentColor"/></svg>',
  pipeline:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 6h7l2 3h7M4 12h5l2 3h9M4 18h16" stroke="currentColor"/><circle cx="4" cy="6" r="1.5" fill="currentColor"/></svg>',
  tcp:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 8h12m-3-3l3 3-3 3M20 16H8m3-3l-3 3 3 3" stroke="currentColor"/></svg>',
  dijkstra:'<svg viewBox="0 0 24 24" fill="none"><path d="M6 17l5-10 7 9M6 17l12-1M11 7l7 9" stroke="currentColor"/><circle cx="6" cy="17" r="2" fill="currentColor"/><circle cx="11" cy="7" r="2" fill="currentColor"/><circle cx="18" cy="16" r="2" fill="currentColor"/></svg>',
  sorting:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 18V9m5 9V5m5 13v-6m5 6V3" stroke="currentColor" stroke-width="2"/><path d="M3 21h19" stroke="currentColor"/></svg>',
  avl:'<svg viewBox="0 0 24 24" fill="none"><path d="M12 5v4M6 18v-4h12v4M6 14l6-5 6 5" stroke="currentColor"/><circle cx="12" cy="4" r="2" fill="currentColor"/><circle cx="6" cy="19" r="2" fill="currentColor"/><circle cx="18" cy="19" r="2" fill="currentColor"/></svg>',
  scheduling:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 7h16M4 12h10M4 17h13" stroke="currentColor"/><circle cx="18" cy="12" r="2" fill="currentColor"/></svg>',
  replacement:'<svg viewBox="0 0 24 24" fill="none"><rect x="5" y="4" width="14" height="16" rx="2" stroke="currentColor"/><path d="M8 9h8M8 13h5m2 3l2 2 3-4" stroke="currentColor"/></svg>',
  congestion:'<svg viewBox="0 0 24 24" fill="none"><path d="M3 18l4-8 4 5 4-11 6 12" stroke="currentColor"/><path d="M3 21h18" stroke="currentColor"/></svg>',
  semaphore:'<svg viewBox="0 0 24 24" fill="none"><rect x="4" y="8" width="16" height="9" rx="2" stroke="currentColor"/><path d="M9 8V5h6v3M8 12h8" stroke="currentColor"/></svg>',
  banker:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 9h16M6 9v9m4-9v9m4-9v9m4-9v9M3 19h18M12 4l8 4H4l8-4z" stroke="currentColor"/></svg>',
  interrupt:'<svg viewBox="0 0 24 24" fill="none"><path d="M12 3v5m0 8v5M3 12h5m8 0h5M5.6 5.6l3.5 3.5m5.8 5.8l3.5 3.5m0-12.8l-3.5 3.5m-5.8 5.8l-3.5 3.5" stroke="currentColor"/><circle cx="12" cy="12" r="3" fill="currentColor"/></svg>',
  cidr:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 6h5v5H4zM15 13h5v5h-5zM9 8.5h4a4 4 0 014 4v.5M7 11v6h8" stroke="currentColor"/></svg>',
  focus:'<svg viewBox="0 0 24 24" fill="none"><path d="M8 4H4v4m12-4h4v4M8 20H4v-4m12 4h4v-4" stroke="currentColor"/></svg>',
  pause:'<svg viewBox="0 0 24 24" fill="none"><path d="M9 7v10M15 7v10" stroke="currentColor" stroke-width="2"/></svg>',
  play:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 6l10 6-10 6z"/></svg>',
  prev:'<svg viewBox="0 0 24 24" fill="none"><path d="M15 6l-6 6 6 6" stroke="currentColor" stroke-width="2"/></svg>',
  next:'<svg viewBox="0 0 24 24" fill="none"><path d="M9 6l6 6-6 6" stroke="currentColor" stroke-width="2"/></svg>',
  reset:'<svg viewBox="0 0 24 24" fill="none"><path d="M19 8a8 8 0 10.5 7M19 8V4m0 4h-4" stroke="currentColor" stroke-width="1.7"/></svg>',
  bulb:'<svg viewBox="0 0 24 24" fill="none"><path d="M9 18h6m-5 3h4m4-10a6 6 0 10-10 4.5c.8.6 1 1.5 1 2.5h6c0-1 .2-1.9 1-2.5A5.9 5.9 0 0018 11z" stroke="currentColor"/></svg>'
};
const LABS={
  memory:{order:1,subject:'组成原理',subjectKey:'computer',title:'虚拟地址，是如何找到物理内存的？',nav:'虚拟内存地址转换',short:'拆开页号与偏移，跟踪 TLB、页表和缺页。',canvas:'地址转换模拟器',version:'4 KiB PAGE · 16 BIT',question:'TLB、页表、缺页异常常被混在一起。跟着一个地址，走完整条翻译链。',principle:'<p><strong>TLB miss ≠ page fault。</strong>前者是翻译缓存没找到，后者是页表有效位为 0。</p>',observation:'切换到“TLB 未命中 · 缺页”，看页表如何把控制权交给操作系统。',exam:'先由页大小确定页内偏移位数，再用“页框号替换页号”。若题目给 TLB / 页表访问时延，要按命中路径分别计算。',legend:[['orange','正在查找'],['green','已确定映射'],['','尚未访问']],params:{scenario:'hit',address:0x73A5},scenarios:[['hit','TLB 命中'],['miss','TLB 未命中 · 页在内存'],['fault','TLB 未命中 · 缺页']]},
  cache:{order:2,subject:'组成原理',subjectKey:'computer',title:'同样的 Cache，为什么命中率不同？',nav:'Cache 映射与替换',short:'让访问序列在三种映射方式里亲自碰撞。',canvas:'Cache 映射观察器',version:'4 LINES · LRU',question:'容量相同，冲突却不同。改变映射方式，观察块能放在哪里、谁会被替换。',principle:'<p><strong>组号 = 块号 mod 组数。</strong>相联度越高，冲突空间越小，但查找硬件越复杂。</p>',observation:'序列 0, 4, 0, 4 在直接映射中持续冲突；全相联则能同时容纳它们。',exam:'先算内存块号，再拆“组号 + 标记”。直接映射每组 1 行；全相联只有 1 组；组相联在组内按题目指定策略替换。',legend:[['green','命中'],['orange','未命中 / 替换'],['','未访问']],params:{mode:'direct',sequence:[0,4,0,4,1,5,1,5]},scenarios:[['direct','直接映射'],['set','2 路组相联'],['full','全相联']]},
  pipeline:{order:3,subject:'组成原理',subjectKey:'computer',title:'流水线，是怎样被数据相关拖慢的？',nav:'指令流水线冒险',short:'从五级流水线时空图看见停顿与前递。',canvas:'五级流水线时空图',version:'IF · ID · EX · MEM · WB',question:'“前递能解决数据相关”并不完整。逐周期看一条依赖链，找到真正必须停顿的位置。',principle:'<p><strong>前递缩短“结果可用”的等待。</strong>但 load 的数据直到 MEM 末才出现，紧邻消费者仍需停 1 拍。</p>',observation:'对比“ALU 相关”和“Load-use 相关”；再关闭前递，观察 ST 格如何增加。右上角同时给出 S=5N/C 与 E=N/C。',exam:'总周期 C = N + 4 + 停顿；加速比 S = 5N/C；效率 E = S/5 = N/C。还要注意题目对寄存器堆同周期读写、前递路径和分支判定阶段的约定。',legend:[['orange','执行 / 停顿'],['green','正常推进'],['blue','访存阶段']],params:{kind:'load',forwarding:true},scenarios:[['load','Load-use 相关'],['alu','连续 ALU 相关']]},
  tcp:{order:4,subject:'计算机网络',subjectKey:'network',title:'ACK 没变，窗口为什么还能滑动？',nav:'TCP 滑动窗口',short:'让分段丢失一次，看累计确认如何跨过缺口。',canvas:'TCP 字节流观察器',version:'CUMULATIVE ACK',question:'窗口不是一排“包”，ACK 也不是包编号。沿着字节序号，看懂连续发送、乱序缓存与累计确认。',principle:'<p><strong>ACK = 下一个期望字节序号。</strong>接收方可以缓存乱序段，但累计 ACK 不能越过缺口。</p>',observation:'把窗口改成 3 段，丢失后重复 ACK 不足 3 个，只能等待超时；改成 4 段可触发快重传。',exam:'TCP 序号按字节计数。发送窗口受 rwnd 和拥塞窗口共同约束；本实验固定 rwnd、忽略 cwnd，只展示累计确认。',legend:[['green','连续已确认'],['blue','乱序缓存'],['orange','在途 / 丢失']],params:{window:4,loss:true},scenarios:[['loss','第 2 段丢失'],['clean','无丢失']]},
  sorting:{order:5,subject:'数据结构',subjectKey:'data',title:'六种内部排序，差别到底发生在哪里？',nav:'排序算法过程对比',short:'同一组数据，切换六种算法并同步观察代码执行。',canvas:'排序算法同步实验',version:'ARRAY · CODE · COUNTERS',question:'同样得到有序序列，比较、移动与分治路径却完全不同。让每一步数组变化和伪代码行严格同步。',principle:'<p><strong>排序算法的差别在过程与约束。</strong>比较次数、移动方式、额外空间、稳定性与初始序列都会影响选择。</p>',observation:'用同一输入切换冒泡、插入、选择、快速、归并和堆排序，观察每次真正改变数组的是哪一行。',exam:'不要只背平均复杂度：插入对近乎有序序列友好；选择交换少但不稳定；快速最坏 O(n²)；归并稳定但需 O(n) 空间；堆排序原地但不稳定。',legend:[['green','已确定位置'],['orange','正在比较 / 移动'],['','未处理']],params:{algo:'bubble',sequence:[7,3,8,2,6,1]},scenarios:[['bubble','冒泡'],['insertion','插入'],['selection','选择'],['quick','快速'],['merge','归并'],['heap','堆']]},
  dijkstra:{order:6,subject:'数据结构',subjectKey:'data',title:'最短路，为什么每次选最近的点？',nav:'Dijkstra 最短路径',short:'逐边松弛，看暂定距离在何时成为最终答案。',canvas:'单源最短路径实验',version:'NON-NEGATIVE GRAPH',question:'“贪心选最小”不是一句口诀。观察非负边权怎样保证：最小暂定距离再也不会被绕路改小。',principle:'<p><strong>确定顶点后，距离不再改变。</strong>这个结论依赖所有边权非负；有负权边请改用其他算法。</p>',observation:'直接点击图中的任意节点可切换源点；调节 C—D 权值，观察最短路径树重构。',exam:'实现时用 dist[]、visited[] 与 prev[]。朴素实现 O(V²)，邻接表配优先队列可到 O((V+E)logV)。',legend:[['green','已确定 / 最短树'],['orange','当前松弛'],['','未确定']],params:{source:0,weight:8},scenarios:[]},
  avl:{order:7,subject:'数据结构',subjectKey:'data',title:'AVL 旋转，究竟在“转”什么？',nav:'AVL 平衡旋转',short:'在四种失衡里追踪高度，而不是背图。',canvas:'AVL 旋转观察器',version:'BALANCE FACTOR',question:'旋转不是换值，而是改链接。让三个键依次插入，看平衡因子如何指向 LL、RR、LR、RL。',principle:'<p><strong>单旋处理“同向”，双旋处理“折线”。</strong>本页按王道常用口径 BF = 左高 − 右高；若教材取反，判型与旋向须整套对应。</p>',observation:'在任意类型中对比旋转前后中序遍历：始终是 10 → 20 → 30。',exam:'插入后从新点向根回溯，处理第一个 |BF| > 1 的祖先。LL/RR 各计 1 次单旋，LR/RL 各计 2 次；旋转前后可用中序序列逐位相同来校验。',legend:[['green','平衡恢复'],['orange','失衡节点'],['','普通节点']],params:{type:'LL'},scenarios:[['LL','LL'],['RR','RR'],['LR','LR'],['RL','RL']]},
  scheduling:{order:8,subject:'操作系统',subjectKey:'os',title:'调度算法，怎样改变每个进程的等待？',nav:'CPU 进程调度',short:'沿甘特图比较 FCFS、SJF 与时间片轮转。',canvas:'CPU 调度时间轴',version:'READY QUEUE · GANTT',question:'平均等待时间不是一张表算出来的，它来自每个时钟周期里谁在运行、谁在队列中等待。',principle:'<p><strong>调度指标来自时间轴。</strong>周转时间 = 完成 − 到达；等待时间 = 周转 − 服务。RR 还需关注时间片与上下文切换。</p>',observation:'在同一负载下切换 FCFS、SJF 与 RR，再调整时间片；观察就绪队列和等待列如何变化。',exam:'FCFS 简单但可能出现护航效应；非抢占 SJF 平均等待较小但依赖服务时间估计；RR 时间片过大趋近 FCFS，过小切换开销高。',legend:[['green','已经完成'],['orange','当前运行'],['','就绪等待']],params:{algo:'fcfs',load:'mix',quantum:2},scenarios:[['fcfs','FCFS'],['sjf','非抢占 SJF'],['rr','时间片轮转']]},
  replacement:{order:9,subject:'操作系统',subjectKey:'os',title:'缺页以后，究竟应该换出哪一页？',nav:'页面置换算法',short:'用同一引用串对比 FIFO、LRU 与理论最优 OPT。',canvas:'页面置换轨迹',version:'FIFO · LRU · OPT',question:'三个页框面对同一引用串，会因为“过去”和“未来”的判断标准不同，产生完全不同的缺页轨迹。',principle:'<p><strong>FIFO 看进入时间，LRU 看过去，OPT 看未来。</strong>OPT 无法在线实现，但能给出理论最少缺页数作为比较基准。</p>',observation:'将页框数从 3 改为 4，对 FIFO 观察缺页数是否一定下降；这正是 Belady 异常的入口。',exam:'命中不置换。FIFO 使用队列；LRU 换出最长时间未访问页；OPT 换出未来最晚使用页。页框数增加时，FIFO 可能反而更多缺页。',legend:[['green','命中'],['orange','缺页 / 置换'],['','未访问']],params:{algo:'fifo',frames:3,refs:[1,2,3,4,1,2,5,1,2,3,4,5]},scenarios:[['fifo','FIFO'],['lru','LRU'],['opt','OPT']]},
  semaphore:{order:10,subject:'操作系统',subjectKey:'os',title:'一个缓冲区，为什么需要三个信号量？',nav:'信号量与同步',short:'跟踪 empty、full、mutex，理解阻塞与唤醒。',canvas:'生产者—消费者同步实验',version:'P / V · BLOCK / WAKE',question:'互斥与同步解决的是不同问题。让生产者和消费者交替运行，看每次 P、V 到底改变了什么。',principle:'<p><strong>资源计数和互斥必须分开。</strong>empty/full 管可用数量，mutex 只保护共享缓冲区；先等资源再拿锁。</p>',observation:'切换到“生产者阻塞”，观察为何 P(empty) 必须发生在 P(mutex) 之前。',exam:'P 操作可能阻塞，V 操作可能唤醒。经典次序：生产者 P(empty)→P(mutex)→放入→V(mutex)→V(full)，消费者对称。',legend:[['orange','当前动作'],['green','可用资源'],['','等待 / 空闲']],params:{scenario:'normal',capacity:3},scenarios:[['normal','正常交替'],['consumer','消费者先阻塞'],['producer','生产者先阻塞']]},
  banker:{order:11,subject:'操作系统',subjectKey:'os',title:'银行家算法，怎样证明系统仍然安全？',nav:'银行家安全性算法',short:'在 Work 与 Need 之间寻找一条安全序列。',canvas:'资源分配安全性检查',version:'AVAILABLE · NEED · WORK',question:'不安全并不等于已经死锁。先做假分配，再亲手寻找一条让所有进程完成的顺序。',principle:'<p><strong>安全状态意味着至少存在一条安全序列。</strong>每次选 Need ≤ Work 的进程，假设其完成并归还 Allocation。</p>',observation:'对比“可安全分配”和“会进入不安全状态”，看假分配为何必须能够撤销。',exam:'先验 Request ≤ Need、Request ≤ Available；假分配后运行安全性算法。找不到安全序列就撤销，并非直接判定当前已死锁。',legend:[['green','已完成'],['orange','当前检查'],['','尚未完成']],params:{request:'safe'},scenarios:[['safe','可安全分配'],['unsafe','导致不安全']]},
  interrupt:{order:12,subject:'组成原理',subjectKey:'computer',title:'中断发生时，CPU 的控制流去了哪里？',nav:'中断响应过程',short:'沿 PC、PSW、向量表与内核栈追踪控制流。',canvas:'中断响应链路',version:'USER → KERNEL → USER',question:'“跳到中断程序”之间省略了什么？逐步观察硬件保护、向量寻址、服务程序与中断返回。',principle:'<p><strong>中断向量保存的是入口线索。</strong>硬件保存最小现场，软件再保存通用寄存器；中断返回恢复 PC 与 PSW。</p>',observation:'对比外部 I/O 中断和同步除零异常：它们进入内核的路径相似，但触发时机与返回语义不同。',exam:'外部中断通常异步、在指令边界响应；异常与当前指令同步。注意题目对断点、现场和向量表内容的具体口径。',legend:[['orange','当前阶段'],['green','已经完成'],['','尚未发生']],params:{kind:'external'},scenarios:[['external','外部 I/O 中断'],['exception','同步除零异常']]},
  congestion:{order:13,subject:'计算机网络',subjectKey:'network',title:'TCP 为什么把窗口画成“锯齿”？',nav:'TCP 拥塞控制',short:'沿 RTT 观察慢开始、拥塞避免与两种丢包恢复。',canvas:'TCP Reno 拥塞窗口',version:'cwnd · ssthresh · RTT',question:'指数增长、线性增长、骤降和折半不是四条口诀，而是发送方根据 ACK 与丢包信号持续调整 cwnd 的结果。',principle:'<p><strong>超时比 3 个重复 ACK 更严重。</strong>经典 Reno 中，超时令 cwnd 回到 1；快重传则把 ssthresh 设为一半后进入快速恢复。</p>',observation:'切换“超时”和“3 个重复 ACK”，再改变初始 ssthresh，观察锯齿拐点与恢复方式。',exam:'发送上限 = min(cwnd, rwnd)。流量控制保护接收方，拥塞控制保护网络。不同 TCP 版本的快速恢复细节可能不同，题目通常按指定版本作答。',legend:[['green','窗口轨迹'],['orange','门限 / 丢包'],['','参考网格']],params:{loss:'timeout',threshold:8,lossRound:6},scenarios:[['timeout','超时丢包'],['dupack','3 个重复 ACK']]},
  cidr:{order:14,subject:'计算机网络',subjectKey:'network',title:'多个网段都匹配，路由器到底选谁？',nav:'CIDR 最长前缀匹配',short:'把目标 IP 化为比特，比较每条路由的匹配长度。',canvas:'路由表最长前缀实验',version:'LONGEST PREFIX MATCH',question:'默认路由、聚合路由和更具体子网可能同时匹配。决定下一跳的是最长前缀，而不是表中先后顺序。',principle:'<p><strong>最长前缀 = 最具体的地址范围。</strong>/20 比 /12 和 /8 更具体；/0 是没有其他匹配时的兜底。</p>',observation:'输入 10.18.35.7、10.19.1.2 或 172.16.0.1，观察候选集合逐步缩小。',exam:'将目标地址和掩码按位与，得到网络号；所有匹配项中选前缀长度最大者。路由聚合不能覆盖不应到达同一下一跳的地址。',legend:[['green','最终选择'],['orange','当前比较'],['','不匹配']],params:{dest:'10.18.35.7'},scenarios:[]}
};
const SUBJECTS=[['all','全部'],['computer','组成原理'],['data','数据结构'],['os','操作系统'],['network','计算机网络']];
const GUIDES={
  memory:{first:'先盯住不变的页内偏移',second:'切换 TLB 命中、未命中和缺页',third:'用页框号重新拼出物理地址',analogy:'把虚拟地址看成“楼栋号 + 房间号”。页表只把楼栋号换成真实楼栋，房间号从头到尾不变。TLB 则是常用楼栋映射的随身便签。',mistake:'TLB 未命中只代表便签没记，不代表页面不在内存。只有查页表发现有效位为 0，才是缺页异常。',transfer:'独立手算多级页表、TLB 命中率和有效访问时间，并准确区分翻译开销与真正的访存次数。'},
  cache:{first:'看块号先被限制到哪一组',second:'观察同组冲突时谁被换出',third:'比较三种映射的命中轨迹',analogy:'像停车场：直接映射是每辆车只有一个固定车位；组相联是只能停某一排；全相联则可以停任何空位。',mistake:'Cache 还有空行不代表一定能放进去。直接映射中，如果目标固定位置被占，仍要发生冲突替换。',transfer:'从地址拆出块内偏移、组号和标记，判断命中，并计算不同相联度下的比较器数量与缺失类型。'},
  pipeline:{first:'横看一条指令经过五个阶段',second:'竖看同一周期哪些阶段并行',third:'定位 ST 气泡和结果可用时刻',analogy:'像五站流水装配线：后车可以进入前一站，但如果所需零件还在前车手里，就必须空出一个工位等待。',mistake:'“有前递就不需要停顿”是错的。load 的数据到 MEM 末才出现，紧邻下一条在 EX 就要用，仍差一个周期。',transfer:'画出时空图，判断 RAW、结构与控制冒险，计算实际周期、加速比和流水线效率。'},
  tcp:{first:'先看 SND.UNA 与 SND.NXT 两条边界',second:'制造一个缺口并观察重复 ACK',third:'看缺口补上后 ACK 一次跃迁',analogy:'像按页码收文件：第 3、4 页先到了可以暂存，但第 2 页没到，就只能继续回复“我下一页还要第 2 页”。',mistake:'ACK 不是“最后收到的段号”，而是下一个期望字节序号。TCP 序号按字节计数，不按报文段计数。',transfer:'手算滑动窗口左右边界、累计确认号、可发送范围，并判断快重传或超时重传何时发生。'},
  sorting:{first:'看橙色柱子对应哪一行代码',second:'逐步比较同一输入下的移动方式',third:'用计数与稳定性解释算法差异',analogy:'把排序看成整理一排不同高度的书：有的只交换相邻书，有的抽出一本插进有序区，有的先分组再合并。',mistake:'只背 O(n²) 或 O(nlogn) 看不出真实差异。比较次数、移动次数、是否稳定、是否原地和初始有序程度都很关键。',transfer:'跟着代码准确手推一趟排序，判断中间序列，分析最好/最坏情形，并解释稳定性为什么被破坏。'},
  dijkstra:{first:'看未确定点中的最小 dist',second:'沿当前点的边逐一做松弛',third:'观察绿色最短路树如何生长',analogy:'像从起点向外涨水：水位最低的边界点最先被淹没。边权非负保证后面的绕路不可能倒流回来变得更短。',mistake:'更新了 dist 不代表该点已经确定。只有它成为未确定集合中的最小值并被选中后，距离才不可再改。',transfer:'手推 dist、visited、prev 三个数组，恢复具体最短路径，并解释为什么负权边会破坏贪心依据。'},
  avl:{first:'先沿插入路径回算高度和 BF',second:'找到离新点最近的失衡祖先',third:'旋转后核对中序序列不变',analogy:'像调整一架失衡的天平：不是把数字换位置，而是改变支点与连接关系，同时保持从左到右的大小顺序。',mistake:'LR/RL 不能直接对失衡点单旋。要先绕孩子把折线拉直，再绕失衡点完成第二次旋转。',transfer:'仅凭插入路径判断四种失衡，正确计算旋转次数，并用中序序列与 BF 双重检查答案。'},
  scheduling:{first:'先读到达时刻与服务时间',second:'看调度点上就绪队列如何变化',third:'从甘特图回算等待与周转时间',analogy:'像只有一个窗口的办事大厅：FCFS 按到达排队，SJF 优先办短业务，RR 则每人只办固定时长就换下一位。',mistake:'等待时间不包含真正占用 CPU 的时间。周转时间减去服务时间，才是进程在就绪队列里累计等待的时间。',transfer:'画甘特图、计算响应/等待/周转时间，并分析时间片大小、护航效应、饥饿与公平性之间的取舍。'},
  replacement:{first:'看当前访问是否已在页框中',second:'缺页时观察算法选中的牺牲页',third:'对比相同引用串的缺页总数',analogy:'像书桌只能摊开几本书：FIFO 扔最早拿来的，LRU 扔最久没翻的，OPT 则假装知道未来，扔最晚才会再用的。',mistake:'命中时 FIFO 的入队时间不更新；LRU 的最近使用时刻会更新。两者看起来相近，但参考信息完全不同。',transfer:'逐步填写页框表、统计缺页率，识别 Belady 异常，并用 OPT 作为其他算法的理论下界。'},
  semaphore:{first:'先分清 empty/full 与 mutex 的职责',second:'跟踪 P 操作何时让进程阻塞',third:'检查 empty + full 是否始终等于 N',analogy:'像餐厅传菜窗口：empty 是空盘位，full 是已有菜盘，mutex 是窗口一次只能伸进一只手。',mistake:'若先 P(mutex) 再等待 empty/full，进程可能抱着锁睡眠，让能释放资源的另一方永远进不了临界区。',transfer:'为生产者—消费者、读者—写者等问题写出正确 PV 次序，并从等待条件判断死锁或同步错误。'},
  banker:{first:'先计算每个进程的 Need',second:'用 Work 试找可完成进程',third:'沿安全序列观察资源逐步回收',analogy:'像银行发放贷款：不是看眼前还有多少钱，而是假设按某个顺序让客户完成并还款，验证所有人最终都能完成。',mistake:'不安全状态不等于已经死锁；它只是不存在可证明的安全完成顺序，继续运行有进入死锁的风险。',transfer:'完成请求预检、假分配与安全性检查，写出安全序列，准确区分安全、不安全和死锁状态。'},
  interrupt:{first:'盯住 PC 和处理器模式的变化',second:'看最小现场何时压入内核栈',third:'沿向量表入口再返回原控制流',analogy:'像上课时消防警报响起：先记住讲到哪一页和当前状态，查应急手册找到处理入口，处理完再回到断点。',mistake:'中断向量通常不是“中断服务程序本身”，而是入口地址或入口线索；硬件现场与软件保存的通用寄存器也要区分。',transfer:'梳理中断请求、响应、处理、返回全过程，比较外部中断、异常、系统调用与 DMA 的角色边界。'},
  congestion:{first:'先看 cwnd 位于 ssthresh 哪一侧',second:'观察 ACK 让窗口翻倍还是线性增大',third:'比较超时与重复 ACK 的降窗幅度',analogy:'像试探一条陌生道路的承载量：先快速加车，接近拥堵后谨慎增加；一旦堵塞，就退回更保守的发送规模。',mistake:'cwnd 是发送方根据网络拥塞维护的窗口，rwnd 是接收方通告的缓存能力；真正发送上限取二者较小值。',transfer:'画出 Tahoe/Reno 典型窗口曲线，判断每轮 cwnd 与 ssthresh，并区分慢开始、拥塞避免和快速恢复。'},
  cidr:{first:'把目标 IP 与前缀都看成 32 位比特',second:'逐条筛出能够匹配的路由',third:'在候选中选择前缀最长者',analogy:'像寄快递：国家、省、市、街道都可能匹配地址，但应优先交给描述最具体的投递点；默认路由只是兜底。',mistake:'最长前缀不是数值最大的网络地址，也不是路由表中最先出现的项，而是掩码中连续 1 的数量最多。',transfer:'进行 CIDR 地址范围、路由聚合和最长前缀匹配计算，判断一个目标地址最终应走哪个下一跳。'}
};
let state={current:'memory',filter:'all',frames:[],step:0,playing:false,timer:null,speed:1,completed:new Set(),focus:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function safeLoad(){try{return new Set(JSON.parse(localStorage.getItem('observatory-completed')||'[]').filter(x=>LABS[x]))}catch{return new Set()}}
state.completed=safeLoad();
function save(){try{localStorage.setItem('observatory-completed',JSON.stringify([...state.completed]))}catch{}}
function navGroup(subject){return Object.entries(LABS).filter(([,l])=>l.subject===subject).sort((a,b)=>a[1].order-b[1].order)}
function renderNav(){const host=$('#lab-nav');host.innerHTML='';[['组成原理','COMPUTER'],['数据结构','DATA'],['操作系统','OPERATING SYSTEM'],['计算机网络','NETWORK']].forEach(([subject,label])=>{const labs=navGroup(subject);if(!labs.length)return;const cap=document.createElement('div');cap.className='nav-group-label';cap.textContent=label;host.append(cap);labs.forEach(([id,lab])=>{const b=document.createElement('button');b.type='button';b.className='nav-item'+(id===state.current?' active':'');b.dataset.lab=id;b.innerHTML=ICONS[id]+`<span>${lab.nav}</span>`+(state.completed.has(id)?'<i class="done-dot"></i>':'');b.onclick=()=>selectLab(id,true);host.append(b)})})}
function renderFilters(){const counts={all:Object.keys(LABS).length};SUBJECTS.slice(1).forEach(([key])=>counts[key]=Object.values(LABS).filter(l=>l.subjectKey===key).length);$('#subject-filters').innerHTML=SUBJECTS.map(([key,label])=>`<button class="filter-button ${key===state.filter?'active':''}" data-filter="${key}" type="button">${label}<small>${String(counts[key]).padStart(2,'0')}</small></button>`).join('');$$('.filter-button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderFilters();renderCards()})}
function cardArt(id){const map={memory:'<rect x="9" y="10" width="46" height="36" rx="5" fill="#edf0e7" stroke="#a9b9aa"/><rect x="25" y="29" width="47" height="28" rx="5" fill="#fff0e6" stroke="#e6a487"/><path d="M37 22v10" stroke="#e66b46"/>',cache:'<path d="M11 49h59M16 39h49M21 29h39M26 19h29" stroke="#8aa08c"/><rect x="21" y="13" width="34" height="11" rx="3" fill="#fff0e6" stroke="#e6a487"/>',pipeline:'<path d="M8 17h18l8 8h38M8 33h12l8 8h44M8 50h64" stroke="#81998b"/><circle cx="9" cy="17" r="4" fill="#e66b46"/>',tcp:'<path d="M9 20h55m-8-7l8 7-8 7M74 45H19m8-7l-8 7 8 7" stroke="#78928a"/><rect x="30" y="14" width="19" height="12" rx="3" fill="#fff0e6" stroke="#e66b46"/>',sorting:'<path d="M12 54V29m14 25V15m14 39V36m14 18V9m14 45V25" stroke="#81988a" stroke-width="5"/><path d="M7 58h70" stroke="#e66b46"/>',dijkstra:'<path d="M11 49L33 12l40 35M11 49l62-2M33 12l40 35" stroke="#8a9e8e"/><circle cx="11" cy="49" r="5" fill="#e66b46"/><circle cx="33" cy="12" r="5" fill="#f4f3ed" stroke="#8a9e8e"/><circle cx="73" cy="47" r="5" fill="#3c7771"/>',avl:'<path d="M42 13v15M18 54V40h48v14M18 40l24-12 24 12" stroke="#8a9e8e"/><circle cx="42" cy="12" r="6" fill="#fff0e6" stroke="#e66b46"/><circle cx="18" cy="55" r="6" fill="#e9f2ec" stroke="#3c7771"/><circle cx="66" cy="55" r="6" fill="#e9f2ec" stroke="#3c7771"/>',semaphore:'<rect x="10" y="20" width="64" height="34" rx="7" fill="#edf1e8" stroke="#8aa08c"/><path d="M24 20V12h36v8M22 37h40" stroke="#e66b46"/><circle cx="27" cy="37" r="5" fill="#e66b46"/>',banker:'<path d="M10 23h64M15 23v31m15-31v31m15-31v31m15-31v31M8 55h68M42 9L73 20H11L42 9z" stroke="#81988a"/>',interrupt:'<circle cx="42" cy="34" r="12" fill="#fff0e6" stroke="#e66b46"/><path d="M42 7v14m0 26v14M15 34h14m26 0h14M23 15l10 10m18 18l10 10" stroke="#879b8d"/>',scheduling:'<path d="M8 17h68M8 31h49M8 45h61" stroke="#81988a" stroke-width="5"/><circle cx="66" cy="31" r="6" fill="#e66b46"/>',replacement:'<rect x="14" y="8" width="56" height="50" rx="6" fill="#edf1e8" stroke="#82988a"/><path d="M24 20h36M24 32h36M24 44h22" stroke="#e66b46"/>',congestion:'<path d="M8 54l11-25 12 14 11-34 14 41 18-28" stroke="#3c7771" stroke-width="2" fill="none"/><path d="M8 57h68M8 25h68" stroke="#d99b7d" stroke-dasharray="4 3"/>',cidr:'<rect x="8" y="13" width="23" height="15" rx="3" fill="#eaf1e8" stroke="#7d9d86"/><rect x="53" y="39" width="23" height="15" rx="3" fill="#fff0e6" stroke="#e66b46"/><path d="M31 20h11c11 0 15 8 15 19M20 28v20h33" stroke="#81978b"/>'};return `<svg class="card-art" viewBox="0 0 84 65" fill="none">${map[id]||''}</svg>`}
function renderCards(){const entries=Object.entries(LABS).filter(([,l])=>state.filter==='all'||l.subjectKey===state.filter);$('#result-count').textContent=entries.length+' 个值得亲手探索的瞬间';$('#empty-state').hidden=entries.length>0;$('#lab-cards').innerHTML=entries.map(([id,l])=>`<button class="lab-card ${id===state.current?'is-current':''}" type="button" data-lab="${id}"><div class="card-overline"><span class="card-number">${String(l.order).padStart(2,'0')}${state.completed.has(id)?'<b class="card-complete">· 已探索</b>':''}</span><span class="card-subject">${l.subject}</span></div>${cardArt(id)}<h4>${l.nav}</h4><p>${l.short}</p><span class="card-arrow">↗</span></button>`).join('');$$('.lab-card').forEach(b=>b.onclick=()=>selectLab(b.dataset.lab,true))}
function renderParams(){const id=state.current,l=LABS[id],p=l.params;let html=l.scenarios.length?'<span class="parameter-label">选择情境</span>'+l.scenarios.map(([v,label])=>`<button type="button" class="scenario-button ${(p.scenario||p.mode||p.kind||p.type||p.algo||p.request||(id==='tcp'?(p.loss?'loss':'clean'):p.loss))==v?'active':''}" data-value="${v}">${label}</button>`).join(''):'';
  if(id==='memory')html+=`<label class="param-group"><span class="parameter-label">虚拟地址</span><input class="param-input" id="address-input" value="${fmtAddress(p.address)}" maxlength="6" inputmode="text"></label><div class="input-error" id="address-error"></div>`;
  if(id==='cache')html+=`<label class="param-group"><span class="parameter-label">块序列</span><input class="param-input" id="sequence-input" value="${p.sequence.join(',')}" style="width:164px" maxlength="42"></label><div class="input-error" id="sequence-error"></div>`;
  if(id==='sorting')html+=`<label class="param-group"><span class="parameter-label">待排序数组</span><input class="param-input" id="sort-input" value="${p.sequence.join(',')}" style="width:154px" maxlength="35"></label><div class="input-error" id="sort-error"></div>`;
  if(id==='pipeline')html+=`<label class="param-group"><input type="checkbox" id="forwarding-input" ${p.forwarding?'checked':''}><span class="parameter-label">开启前递</span></label>`;
  if(id==='tcp')html+=`<label class="param-group"><span class="parameter-label">窗口 ${p.window} 段</span><input class="param-range" id="window-input" type="range" min="2" max="6" value="${p.window}"></label>`;
  if(id==='dijkstra')html+=`<label class="param-group"><span class="parameter-label">起点</span><select class="param-select" id="source-input">${['A','B','C','D','E','F'].map((n,i)=>`<option value="${i}" ${p.source===i?'selected':''}>${n}</option>`).join('')}</select></label><label class="param-group"><span class="parameter-label">C—D 权值 ${p.weight}</span><input class="param-range" id="weight-input" type="range" min="1" max="15" value="${p.weight}"></label>`;
  if(id==='scheduling')html+=`<label class="param-group"><span class="parameter-label">负载</span><select class="param-select" id="load-input"><option value="mix" ${p.load==='mix'?'selected':''}>同时到达较多</option><option value="staggered" ${p.load==='staggered'?'selected':''}>错峰到达</option></select></label>${p.algo==='rr'?`<label class="param-group"><span class="parameter-label">时间片 ${p.quantum}</span><input class="param-range" id="quantum-input" type="range" min="1" max="4" value="${p.quantum}"></label>`:''}`;
  if(id==='replacement')html+=`<label class="param-group"><span class="parameter-label">页框数 ${p.frames}</span><input class="param-range" id="pageframes-input" type="range" min="2" max="5" value="${p.frames}"></label><label class="param-group"><span class="parameter-label">引用串</span><input class="param-input" id="refs-input" value="${p.refs.join(',')}" style="width:190px" maxlength="45"></label><div class="input-error" id="refs-error"></div>`;
  if(id==='semaphore')html+=`<label class="param-group"><span class="parameter-label">缓冲区容量 ${p.capacity}</span><input class="param-range" id="capacity-input" type="range" min="2" max="5" value="${p.capacity}"></label>`;
  if(id==='congestion')html+=`<label class="param-group"><span class="parameter-label">初始门限 ${p.threshold}</span><input class="param-range" id="threshold-input" type="range" min="4" max="16" step="2" value="${p.threshold}"></label><label class="param-group"><span class="parameter-label">丢包轮次 ${p.lossRound}</span><input class="param-range" id="lossround-input" type="range" min="3" max="10" value="${p.lossRound}"></label>`;
  if(id==='cidr')html+=`<label class="param-group"><span class="parameter-label">目标 IP</span><input class="param-input" id="ip-input" value="${p.dest}" style="width:116px" maxlength="15"></label><div class="input-error" id="ip-error"></div>`;
  $('#parameter-bar').innerHTML=html;
  $$('.scenario-button').forEach(b=>b.onclick=()=>{if(id==='memory'||id==='semaphore')p.scenario=b.dataset.value;if(id==='cache')p.mode=b.dataset.value;if(id==='pipeline'||id==='interrupt')p.kind=b.dataset.value;if(id==='tcp')p.loss=b.dataset.value==='loss';if(id==='avl')p.type=b.dataset.value;if(id==='sorting'||id==='scheduling'||id==='replacement')p.algo=b.dataset.value;if(id==='banker')p.request=b.dataset.value;if(id==='congestion')p.loss=b.dataset.value;rebuild(true)});
  const bind=(sel,event,fn)=>{const el=$(sel);if(el)el.addEventListener(event,fn)};
  bind('#address-input','change',e=>{const raw=e.target.value.trim(),n=/^0x[\da-f]+$/i.test(raw)?parseInt(raw,16):/^\d+$/.test(raw)?parseInt(raw,10):NaN;if(!Number.isInteger(n)||n<0||n>65535){$('#address-error').textContent='请输入 0x0000–0xFFFF 或 0–65535。';e.target.value=fmtAddress(p.address);return}p.address=n;rebuild(true)});
  bind('#sequence-input','change',e=>{const a=e.target.value.split(/[,，\s]+/).filter(Boolean).map(Number);if(!a.length||a.length>16||a.some(n=>!Number.isInteger(n)||n<0||n>31)){const err=$('#sequence-error');err.textContent='输入 1–16 个 0–31 的整数，用逗号分隔。';e.target.value=p.sequence.join(',');return}p.sequence=a;rebuild(true)});
  bind('#sort-input','change',e=>{const a=e.target.value.split(/[,，\s]+/).filter(Boolean).map(Number);if(a.length<2||a.length>8||a.some(n=>!Number.isInteger(n)||n<0||n>99)){const err=$('#sort-error');err.textContent='输入 2–8 个 0–99 的整数，用逗号分隔。';e.target.value=p.sequence.join(',');return}p.sequence=a;rebuild(true)});
  bind('#forwarding-input','change',e=>{p.forwarding=e.target.checked;rebuild(true)});
  bind('#window-input','input',e=>{p.window=+e.target.value;rebuild(true)});
  bind('#source-input','change',e=>{p.source=+e.target.value;rebuild(true)});
  bind('#weight-input','input',e=>{p.weight=+e.target.value;rebuild(true)});
  bind('#load-input','change',e=>{p.load=e.target.value;rebuild(true)});
  bind('#quantum-input','input',e=>{p.quantum=+e.target.value;rebuild(true)});
  bind('#pageframes-input','input',e=>{p.frames=+e.target.value;rebuild(true)});
  bind('#refs-input','change',e=>{const a=e.target.value.split(/[,，\s]+/).filter(Boolean).map(Number);if(a.length<3||a.length>18||a.some(n=>!Number.isInteger(n)||n<0||n>9)){const err=$('#refs-error');err.textContent='输入 3–18 个 0–9 的页号，用逗号分隔。';e.target.value=p.refs.join(',');return}p.refs=a;rebuild(true)});
  bind('#capacity-input','input',e=>{p.capacity=+e.target.value;rebuild(true)});
  bind('#threshold-input','input',e=>{p.threshold=+e.target.value;rebuild(true)});
  bind('#lossround-input','input',e=>{p.lossRound=+e.target.value;rebuild(true)});
  bind('#ip-input','change',e=>{const raw=e.target.value.trim(),parts=raw.split('.').map(Number);if(parts.length!==4||parts.some(n=>!Number.isInteger(n)||n<0||n>255)){const err=$('#ip-error');err.textContent='请输入合法 IPv4 地址，例如 10.18.35.7。';e.target.value=p.dest;return}p.dest=parts.join('.');rebuild(true)});
}
function fmtAddress(n){return '0x'+n.toString(16).toUpperCase().padStart(4,'0')}
function updateProgress(){const n=state.completed.size,total=Object.keys(LABS).length;$('#progress-count').textContent=n+' / '+total;$('#progress-fill').style.width=(n/total*100)+'%'}
function selectLab(id,scroll=false){if(!LABS[id])return;stop();state.current=id;state.step=0;renderNav();renderCards();rebuild(false);document.body.classList.remove('menu-open');$('#menu-toggle').setAttribute('aria-expanded','false');if(scroll)$('#experiment').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}
function rebuild(paramsOnly){stop();const l=LABS[state.current];state.frames=Models[state.current](l.params);state.step=0;renderHeader();renderParams();renderFrame();if(paramsOnly)renderCards()}
function renderHeader(){const l=LABS[state.current],g=GUIDES[state.current];$('#lab-kicker').innerHTML=`<span class="lab-number">${String(l.order).padStart(2,'0')}</span><i></i><span>${l.subject}</span>`;$('#lab-title').textContent=l.title;$('#lab-question').textContent=l.question;$('#canvas-label').textContent=l.canvas;$('#canvas-version').textContent=l.version;$('#principle-content').innerHTML=l.principle;$('#observation-note').textContent=l.observation;$('#exam-note').textContent=l.exam;$('#stage-legend').innerHTML=l.legend.map(([c,label])=>`<span><i class="legend-square ${c}"></i>${label}</span>`).join('');$('#guide-first').textContent=g.first;$('#guide-second').textContent=g.second;$('#guide-third').textContent=g.third;$('#analogy-text').textContent=g.analogy;$('#mistake-text').textContent=g.mistake;$('#transfer-text').textContent=g.transfer}
function renderFrame(){const frame=state.frames[state.step];if(!frame)return;$('#visual-stage').dataset.lab=state.current;$('#visual-stage').innerHTML=renderVisualization(state.current,frame,state.step,state.frames.length);$('#step-pill').textContent=`STEP ${String(state.step+1).padStart(2,'0')}`;$('#step-explanation').innerHTML=`<h3 class="step-title">${frame.title}</h3><p class="step-copy">${frame.copy}</p><div class="step-formula">${frame.formula}</div>`;$('#frame-counter').textContent=`${String(state.step+1).padStart(2,'0')} / ${String(state.frames.length).padStart(2,'0')}`;const tl=$('#timeline');tl.max=state.frames.length-1;tl.value=state.step;tl.style.setProperty('--progress',(state.frames.length===1?100:state.step/(state.frames.length-1)*100)+'%');$('#prev-button').disabled=state.step===0;$('#next-button').disabled=state.step===state.frames.length-1;$('#play-button').innerHTML=state.playing?ICONS.pause+' 暂停':ICONS.play+(state.step===state.frames.length-1?' 再看一次':' 播放推演');$('#play-button').setAttribute('aria-label',state.playing?'暂停推演':'播放推演');$('#step-explanation').classList.remove('changed');void $('#step-explanation').offsetWidth;$('#step-explanation').classList.add('changed');bindSvgInteractions();if(state.step===state.frames.length-1&&!state.completed.has(state.current)){state.completed.add(state.current);save();updateProgress();renderNav();renderCards();toast('已完成「'+LABS[state.current].nav+'」探索')}}
function bindSvgInteractions(){if(state.current!=='dijkstra')return;$$('#visual-stage [data-source]').forEach(g=>{const use=()=>{LABS.dijkstra.params.source=+g.dataset.source;rebuild(true)};g.addEventListener('click',use);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();use()}})})}
function step(delta){stop();state.step=Math.max(0,Math.min(state.frames.length-1,state.step+delta));renderFrame()}
function togglePlay(){if(state.playing){stop();return}if(state.step>=state.frames.length-1)state.step=0;state.playing=true;renderFrame();schedule()}
function schedule(){clearTimeout(state.timer);if(!state.playing)return;const ms=1300/state.speed;state.timer=setTimeout(()=>{if(state.step>=state.frames.length-1){stop();return}state.step++;renderFrame();if(state.step>=state.frames.length-1)stop();else schedule()},ms)}
function stop(){state.playing=false;clearTimeout(state.timer);state.timer=null;if(state.frames.length)renderPlayButtonOnly()}
function renderPlayButtonOnly(){const b=$('#play-button');if(!b)return;b.innerHTML=ICONS.play+(state.step===state.frames.length-1?' 再看一次':' 播放推演');b.setAttribute('aria-label','播放推演')}
let toastTimer;function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2200)}
function init(){
  $('#nav-count').textContent=String(Object.keys(LABS).length).padStart(2,'0');$('#hero-lab-count').textContent=String(Object.keys(LABS).length).padStart(2,'0');$('#focus-button').innerHTML=ICONS.focus;$('#prev-button').innerHTML=ICONS.prev;$('#next-button').innerHTML=ICONS.next;$('#reset-button').innerHTML=ICONS.reset;$('#insight-icon').innerHTML=ICONS.bulb;
  renderNav();renderFilters();renderCards();updateProgress();rebuild(false);
  $('#play-button').onclick=togglePlay;$('#prev-button').onclick=()=>step(-1);$('#next-button').onclick=()=>step(1);$('#reset-button').onclick=()=>{stop();state.step=0;renderFrame()};$('#timeline').oninput=e=>{stop();state.step=+e.target.value;renderFrame()};$('#speed-select').onchange=e=>{state.speed=+e.target.value;if(state.playing)schedule()};
  const closeZoom=()=>{document.body.classList.remove('visual-zoom');$('#visual-stage').classList.remove('zoom-stage');document.querySelector('.zoom-backdrop')?.remove();$('#zoom-button').textContent='放大图解 ↗'};
  $('#zoom-button').onclick=()=>{if(document.body.classList.contains('visual-zoom')){closeZoom();return}stop();document.body.classList.add('visual-zoom');$('#visual-stage').classList.add('zoom-stage');const bg=document.createElement('div');bg.className='zoom-backdrop';bg.onclick=closeZoom;document.body.append(bg);$('#zoom-button').textContent='退出放大 ×';toast('图解已放大 · 可左右滚动查看')};$('#zoom-close').onclick=closeZoom;
  $('#focus-button').onclick=()=>{state.focus=!state.focus;document.body.classList.toggle('focus-mode',state.focus);$('#focus-button').setAttribute('aria-pressed',state.focus);toast(state.focus?'已进入专注模式 · Esc 退出':'已退出专注模式')};
  $('#menu-toggle').innerHTML='<span style="font-size:17px">☰</span>';$('#menu-toggle').onclick=()=>{const open=document.body.classList.toggle('menu-open');$('#menu-toggle').setAttribute('aria-expanded',open)};$('#menu-overlay').onclick=()=>document.body.classList.remove('menu-open');
  $('#help-button').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();$('#help-dialog').onclick=e=>{if(e.target===$('#help-dialog'))$('#help-dialog').close()};
  $('#clear-progress').onclick=()=>{state.completed.clear();save();updateProgress();renderNav();renderCards();toast('学习记录已重置')};$('#back-top').onclick=()=>scrollTo({top:0,behavior:'smooth'});
  document.addEventListener('keydown',e=>{if(e.target.matches('input,select,button')||$('#help-dialog').open)return;if(e.key===' '){e.preventDefault();togglePlay()}else if(e.key==='ArrowRight')step(1);else if(e.key==='ArrowLeft')step(-1);else if(e.key.toLowerCase()==='r'){stop();state.step=0;renderFrame()}else if(e.key==='Escape'&&document.body.classList.contains('visual-zoom')){$('#zoom-button').click()}else if(e.key==='Escape'&&state.focus){state.focus=false;document.body.classList.remove('focus-mode')}});
}
document.addEventListener('DOMContentLoaded',init);
